apiVersion: v1
kind: PersistentVolume
metadata:
  name: budget-analysis-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: budget-analysis-nfs
  nfs:
    server: vanaheim.lan
    path: /srv/budget-analysis
