apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: budget-analysis-data
  namespace: budget-analysis
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: budget-analysis-nfs
  resources:
    requests:
      storage: 10Gi
  volumeName: budget-analysis-data-pv
